### PR TITLE
Add unyt

### PR DESCRIPTION
**Pull request by rmatsum836**
Addressing #21, incorporating unyt into `runners.py` so that units are tracked and verified before being written out.  More specifically, the arguments and kwargs are checked.  If a unyt array is passed, then the units are converted to Cassandra units.  If a unyt array isn't passed, then a warning message is printed to notify the user that the unit in Cassandra is assumed.

This is very much a work on progress, but wanted to get feedback before proceeding.  I'm sure I'm missing some kwargs that need to be accounted for, as well as adding some unit tests specific to this addition.  Feel free to provide any comments or criticisms.

### CODE REVIEW

**Comment by rmatsum836** [comment]
I think I agree that units should be tracked until the writer stage.  I'm just now seeing that there are lots of nm to angstrom conversions in `inp_functions.py` as well so it seems like a more natural place to check units.

>Alternatively, I'm not sure I'm opposed to simply requiring units to be specified. Its a minor inconvenience for the user that will more than repay itself in catching mistakes.

In GMSO, if units aren't specified then the user is warned that units are assumed.  But I can see the case for requiring units in the case of this package since MoSDeF and Cassandra have different base units.

>It looks like the AZP builds for bleeding mosdef tools don't use the requirements files. Therefore, unyt is not installed. This is something that we can address.

This sounds easy enough.  In the future, I might request access to the mosdef_cassandra AZP account so I can monitor the status of these builds if that's okay.  Thanks!

**Comment by rsdefever** [comment]
> In GMSO, if units aren't specified then the user is warned that units are assumed. But I can see the case for requiring units in the case of this package since MoSDeF and Cassandra have different base units.

The more I think about it the more I lean towards requiring units. Why shouldn't we? It's nonsensical to provide a pressure without specifying units. Ditto with temperature, chemical potential, or most other parameters we specify in molecular simulation. Imagine being able to run a simulation without having to waste time looking up the unit system of the software you are using. 

> This sounds easy enough. In the future, I might request access to the mosdef_cassandra AZP account so I can monitor the status of these builds if that's okay. Thanks!

Happy to give you access if/when you need it. We can also fix the AZP issues in a separate PR and I'm happy to help with that as needed.

**Comment by rmatsum836** [comment]
Slowly working through this.  Might have to close this and reopen another PR since the repo was moved to another organization.

**Comment by rsdefever** [comment]
> Slowly working through this. Might have to close this and reopen another PR since the repo was moved to another organization.

No worries. I sincerely appreciate the contribution, its non-trivial. Whenever you want feel free to close this PR and open a new one. Sorry about the repo migration -- had to happen at some point.

**Comment by rmatsum836** [comment]
Going to close this and reopen as a new PR.

**Pull request closed without merging**
