### PR TITLE
Update GCMC adsorption example to CIF + zeolite

### LINKED ISSUE #79: Update adsorption example to use zeolite with CIF file
The adsorption example in the [docs](https://mosdef-cassandra.readthedocs.io/en/latest/getting_started/examples.html) is not very realistic. We should update it to use the new `load_cif` capability from `mbuild` for an example of adsorption in a zeolite.

### PR DESCRIPTION
**Pull request by rsdefever**
Now that `mbuild` contains the CIF reader, the adsorption example is updated to be more realistic.

The example now uses adsorption of methane in TON with TraPPE-zeo for TON and TraPPE-UA for methane.

Closes #79.

### CODE REVIEW

**Review by rmatsum836 — APPROVED** [review]
I'm not too familiar with the `CIF` file format but I ran the `gcmc_adsorption` example and the unit tests in `test_examples.py`.  Everything is passing.

**Comment by rsdefever** [comment]
@rmatsum836 are you OK with some of the file reorganization I did as part of this PR. Looks reasonable?

**Review by rwsmith7531 — APPROVED** [review]
The new example worked for me once I realized I had to use `pip install -e .` instead of `pip install .` and removed an old source installation of Cassandra from my path in my `.bashrc` so mosdef_cassandra would use the conda installation of Cassandra.

**Comment by rsdefever** [comment]
@rwsmith7531 can you elaborate on what was going wrong with `pip install .`? I think we should be able to fix your issue so either can work.

**Comment by rwsmith7531** [comment]
@rsdefever  I got the following error:
```
Traceback (most recent call last):
  File "gcmc_adsorption.py", line 68, in <module>
    run_gcmc_adsorption()
  File "gcmc_adsorption.py", line 16, in run_gcmc_adsorption
    lattice = mbuild.lattice.load_cif(get_example_cif_path("TON"))
  File "/home/rwsmith7531/miniconda3/envs/test/lib/python3.7/site-packages/mbuild/lattice.py", line 30, in load_cif
    with open(cif_location.absolute(), 'r') as cif_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rwsmith7531/miniconda3/envs/test/lib/python3.7/site-packages/mosdef_cassandra/examples/resources/cif_files/TON.cif'
```


I looked into it and saw that there was no `/resources/` subdirectory in the `.../examples/` directory.  I eventually found that installing in development mode (`-e`) avoids that problem, and removes `mosdef_cassandra/` from `site-packages/`  entirely, since the installation is directly based on the local source repo.

**Comment by rwsmith7531** [comment]
In case you were wondering, I ran `pip install .` with this pull request checked out.  It wasn't just an old installation.

**Comment by rsdefever** [comment]
No, this is a good catch. We should be able to fix this. I'll look at it more closely after the holiday.

**Comment by rsdefever** [comment]
@rwsmith7531 I think I fixed the problem you found, re-pull the PR branch and re-run `pip install .` and then try the tests again.

**Pull request merged**
